platform:ios,'8.0'
target ‘downloadImageDemo’ do
    use_frameworks!
    pod 'WeexSDK'
    pod 'WXDevtool', :configurations => ['Debug'] #只在 debug 时引入
    pod 'SocketRocket'
    pod 'SDWebImage' , '~>3.8.2'

end
